In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install openpyxl==3.0.0

     |████████████████████████████████| 172 kB 27.0 MB/s 
  Created wheel for openpyxl: filename=openpyxl-3.0.0-py2.py3-none-any.whl size=241207 sha256=71fb48a102738985ae3b7b17a395305bc7202b5f76a915bda023fa6b4f8ce9b9
  Stored in directory: /root/.cache/pip/wheels/c7/64/ff/ce98f6e1d2701ae8e216c875da62feed2839ac8a3cae0ab8af
Successfully built openpyxl
  Attempting uninstall: openpyxl
    Found existing installation: openpyxl 3.0.9
    Uninstalling openpyxl-3.0.9:
      Successfully uninstalled openpyxl-3.0.9


In [ ]:
import pandas as pd
yr_2001 = pd.read_excel('/content/drive/MyDrive/dataset- lat-long-yield yearwise/2001_lat-long-yield.xlsx',nrows=32147)
yr_2003 = pd.read_excel('/content/drive/MyDrive/dataset- lat-long-yield yearwise/2003_lat-long-yield.xlsx',nrows=23157)
yr_2004 = pd.read_excel('/content/drive/MyDrive/dataset- lat-long-yield yearwise/2004_lat-long-yield.xlsx',nrows=24984)
yr_2005 = pd.read_excel('/content/drive/MyDrive/dataset- lat-long-yield yearwise/2005_lat-long-yield.xlsx',nrows=25857)
yr_2006 = pd.read_excel('/content/drive/MyDrive/dataset- lat-long-yield yearwise/2006_lat-long-yield.xlsx',nrows=22393)
yr_2007 = pd.read_excel('/content/drive/MyDrive/dataset- lat-long-yield yearwise/2007_lat-long-yield.xlsx',nrows=19856)
yr_2008 = pd.read_excel('/content/drive/MyDrive/dataset- lat-long-yield yearwise/2008_lat-long-yield.xlsx',nrows=23501)
yr_2009 = pd.read_excel('/content/drive/MyDrive/dataset- lat-long-yield yearwise/2009_lat-long-yield.xlsx',nrows=25142)
yr_2010 = pd.read_excel('/content/drive/MyDrive/dataset- lat-long-yield yearwise/2010_lat-long-yield.xlsx',nrows=29970)
yr_2011 = pd.read_excel('/content/drive/MyDrive/dataset- lat-long-yield yearwise/2011_lat-long-yield.xlsx',nrows=34785)
yr_2012 = pd.read_excel('/content/drive/MyDrive/dataset- lat-long-yield yearwise/2012_lat-long-yield.xlsx',nrows=23373)


In [ ]:
yr_2001

long        lat  yield   crop   Unnamed: 4    year
0     -85.377393  42.408008   0.00  wheat -21474836.48  2001.0
1     -85.377387  42.407906  45.58  wheat        13.91  2001.0
2     -85.377387  42.407917  39.31  wheat        13.91  2001.0
3     -85.377387  42.407934  39.31  wheat        13.91  2001.0
4     -85.377387  42.407945  49.11  wheat        13.91  2001.0
...          ...        ...    ...    ...          ...     ...
32141 -85.368070  42.410273  51.90  wheat        13.08  2001.0
32142 -85.368070  42.410286  53.91  wheat        13.08  2001.0
32143 -85.368070  42.410301  58.93  wheat        13.08  2001.0
32144 -85.368070  42.410314  53.91  wheat        13.08  2001.0
32145 -85.368065  42.410186   0.65  wheat        13.08  2001.0

[32146 rows x 6 columns]

In [ ]:
X_2001 = yr_2001.iloc[:,[0,1,2]].values
X_2003 = yr_2003.iloc[:,[0,1,2]].values
X_2004 = yr_2004.iloc[:,[0,1,2]].values
X_2005 = yr_2005.iloc[:,[0,1,2]].values
X_2006 = yr_2006.iloc[:,[0,1,2]].values
X_2007 = yr_2007.iloc[:,[0,1,2]].values
X_2008 = yr_2008.iloc[:,[0,1,2]].values
X_2009 = yr_2009.iloc[:,[0,1,2]].values
X_2010 = yr_2010.iloc[:,[0,1,2]].values
X_2011 = yr_2011.iloc[:,[0,1,2]].values
X_2012 = yr_2012.iloc[:,[0,1,2]].values

In [ ]:
for i in range(0,5,1):
  print(X_2004[i])

[-85.37737353  42.40777243  60.56      ]
[-85.37737353  42.40779134  57.55      ]
[-85.37737353  42.40781114  53.82      ]
[-85.37737353  42.40782824  52.34      ]
[-85.37737353  42.40784715  51.46      ]


In [ ]:
qgis = pd.read_excel('/content/drive/MyDrive/qgis - lat-long of images.xlsx',nrows=253)
qgislatlong = qgis.iloc[:,[0,1,2,3,4,5,6,7,8]].values

In [ ]:
qgislatlong[251]

array([252.        , -85.3704294 ,  42.40720012, -85.36897169,
        42.40717939, -85.36900668,  42.40582903, -85.37046436,
        42.40584977])

In [ ]:
noRC= pd.read_excel('/content/drive/MyDrive/image pixel-rows cols.xlsx',nrows=505)
numberRC = noRC.iloc[:,[0,1,2,3]].values

In [ ]:
numberRC[503]

array([504.,  20.,   4.,   5.])

In [ ]:
X_2001.size/X_2001[0].size

32146.0

In [ ]:
X_2001[0]

array([-85.37739288,  42.40800848,   0.        ])

In [ ]:
from shapely.geometry import Point
from shapely.geometry.polygon import Polygon
import numpy as np

In [ ]:
chan=(3,2)
chan=np.zeros(chan)
chan

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Year 2001

In [ ]:
pixelYield_2001=[]
for j in range(0,24,1):
  x1=qgislatlong[j][1]
  y1=qgislatlong[j][2]
  x2=qgislatlong[j][3]
  y2=qgislatlong[j][4]
  x3=qgislatlong[j][5]
  y3=qgislatlong[j][6]
  x4=qgislatlong[j][7]
  y4=qgislatlong[j][8]
  farmPoly = Polygon(np.array([[x1,y1],[x2,y2],[x3,y3],[x4,y4]]))
  nrow=numberRC[j][3]
  ncol=numberRC[j][2]
  yd=(int(nrow),int(ncol))
  yd=np.zeros(yd)
  countyd=(int(nrow),int(ncol))
  countyd = np.zeros(countyd)
  horizontaldiff_x = (x2-x1)/ncol;
  verticaldiff_y = (y4-y1)/nrow;
  ans=(int(nrow),int(ncol))
  ans=np.zeros(ans)
  for i in range(0,int(X_2001.size/X_2001[0].size),1):
    point=Point(X_2001[i][0],X_2001[i][1])
    if point.within(farmPoly):
      for r in range(0,int(nrow),1):
        for c in range(0,int(ncol),1):
          pixelPoly= Polygon(np.array([[x1+(c*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)],[x1+((c)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)]]))
          if point.within(pixelPoly):
            yd[r][c]+=X_2001[i][2]
            countyd[r][c]+=1
  for k in range(0,int(nrow),1):
    for m in range(0,int(ncol),1):
      if countyd[k][m]!=0:
        ans[k][m]=yd[k][m]/countyd[k][m]
  pixelYield_2001.append(ans)

In [ ]:
pixelYield_2001

[array([[ 22.44733333,  27.06982143,  35.75      ,  44.9716    ],
        [ 37.03911765,  44.21717742,  49.35563636,  48.3822619 ],
        [ 37.81857143,  41.79210938,  53.81545455,  48.24964286],
        [173.05368421,  31.19976   ,  40.99298969,  36.72648649],
        [ 44.90333333,   0.        ,   0.        ,   0.        ]]),
 array([[45.95803571, 40.46957746, 42.78456522, 43.73070175],
        [47.86373494, 49.42338843, 50.21765101, 43.29877551],
        [48.46928571, 50.46974576, 51.88583893, 46.97378947],
        [34.41      , 39.76868687, 44.87904762, 38.41      ]]),
 array([[44.59324324, 39.0576087 , 45.59178947, 44.1064    ],
        [56.77052632, 56.8692562 , 56.72970149, 54.18319149],
        [56.30310345, 55.17540984, 55.86969697, 56.203125  ],
        [46.23530612, 45.64072727, 48.84936937, 39.44107143]]),
 array([[34.05112676, 39.72123711, 44.29628099, 37.79714286,  0.        ],
        [ 0.85      , 34.83803571, 29.12659259, 26.6927957 ,  0.        ],
        [ 0.      

Year 2003

In [ ]:
pixelYield_2003=[]
for j in range(24,48,1):
  x1=qgislatlong[j][1]
  y1=qgislatlong[j][2]
  x2=qgislatlong[j][3]
  y2=qgislatlong[j][4]
  x3=qgislatlong[j][5]
  y3=qgislatlong[j][6]
  x4=qgislatlong[j][7]
  y4=qgislatlong[j][8]
  farmPoly = Polygon(np.array([[x1,y1],[x2,y2],[x3,y3],[x4,y4]]))
  nrow=numberRC[j][3]
  ncol=numberRC[j][2]
  yd=(int(nrow),int(ncol))
  yd=np.zeros(yd)
  countyd=(int(nrow),int(ncol))
  countyd = np.zeros(countyd)
  horizontaldiff_x = (x2-x1)/ncol;
  verticaldiff_y = (y4-y1)/nrow;
  ans=(int(nrow),int(ncol))
  ans=np.zeros(ans)
  for i in range(0,int(X_2003.size/X_2003[0].size),1):
    point=Point(X_2003[i][0],X_2003[i][1])
    if point.within(farmPoly):
      for r in range(0,int(nrow),1):
        for c in range(0,int(ncol),1):
          pixelPoly= Polygon(np.array([[x1+(c*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)],[x1+((c)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)]]))
          if point.within(pixelPoly):
            yd[r][c]+=X_2003[i][2]
            countyd[r][c]+=1
  for k in range(0,int(nrow),1):
    for m in range(0,int(ncol),1):
      if countyd[k][m]!=0:
        ans[k][m]=yd[k][m]/countyd[k][m]
  pixelYield_2003.append(ans)

In [ ]:
pixelYield_2003

[array([[ 7.50375   ,  9.8055    , 13.90944444, 12.963125  ],
        [16.88185185, 17.35      , 19.39976744, 18.88692308],
        [17.24555556, 18.39858696, 18.19402062, 19.45352941],
        [16.06      , 19.12276596, 16.31727273, 16.7075    ],
        [12.05684211,  0.        ,  0.        , 11.33818182]]),
 array([[13.36857143, 14.29836066, 14.3047619 , 10.47898305],
        [18.90019608, 15.53595238, 16.54375   , 16.68424658],
        [19.48846154, 15.83926829, 17.29934783, 18.00082192],
        [16.52717391, 15.51736111, 13.4725    , 17.54086207]]),
 array([[ 7.9       ,  7.16714286, 14.48546667, 12.56052632],
        [17.75175   , 18.83569892, 16.54370787, 15.82428571],
        [17.18947368, 18.61032967, 16.19034884, 15.94973684],
        [15.41454545, 15.39310811, 14.20135135, 15.42344828]]),
 array([[16.59608696, 15.18269841, 13.52552941, 17.58222222,  0.        ],
        [11.6625    , 13.52901408, 13.47144578, 11.18394366,  0.        ],
        [15.50692308, 15.25453333, 15.

Year 2004

In [ ]:
pixelYield_2004=[]
for j in range(48,72,1):
  x1=qgislatlong[j][1]
  y1=qgislatlong[j][2]
  x2=qgislatlong[j][3]
  y2=qgislatlong[j][4]
  x3=qgislatlong[j][5]
  y3=qgislatlong[j][6]
  x4=qgislatlong[j][7]
  y4=qgislatlong[j][8]
  farmPoly = Polygon(np.array([[x1,y1],[x2,y2],[x3,y3],[x4,y4]]))
  nrow=numberRC[j][3]
  ncol=numberRC[j][2]
  yd=(int(nrow),int(ncol))
  yd=np.zeros(yd)
  countyd=(int(nrow),int(ncol))
  countyd = np.zeros(countyd)
  horizontaldiff_x = (x2-x1)/ncol;
  verticaldiff_y = (y4-y1)/nrow;
  ans=(int(nrow),int(ncol))
  ans=np.zeros(ans)
  for i in range(0,int(X_2004.size/X_2004[0].size),1):
    point=Point(X_2004[i][0],X_2004[i][1])
    if point.within(farmPoly):
      for r in range(0,int(nrow),1):
        for c in range(0,int(ncol),1):
          pixelPoly= Polygon(np.array([[x1+(c*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)],[x1+((c)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)]]))
          if point.within(pixelPoly):
            yd[r][c]+=X_2004[i][2]
            countyd[r][c]+=1
  for k in range(0,int(nrow),1):
    for m in range(0,int(ncol),1):
      if countyd[k][m]!=0:
        ans[k][m]=yd[k][m]/countyd[k][m]
  pixelYield_2004.append(ans)

In [ ]:
pixelYield_2004

[array([[30.41923077, 32.62058824, 44.17534483, 48.48944444],
        [52.912     , 46.18957895, 56.61485714, 53.93344828],
        [53.79826923, 45.66084211, 57.47067308, 52.70442623],
        [50.76447368, 43.83505747, 51.08853933, 46.46692308],
        [47.53037037,  0.        ,  0.        , 27.39214286]]),
 array([[49.27175   , 36.88828947, 41.25892857, 44.671875  ],
        [53.68175439, 44.49025862, 49.20405941, 50.64823529],
        [52.68467742, 48.21439655, 51.35355769, 54.1109589 ],
        [46.28983871, 44.99169811, 43.81564103, 44.3579661 ]]),
 array([[46.43410256, 45.84297619, 49.05913043, 45.02571429],
        [53.98034483, 54.2801    , 57.06125   , 63.74631579],
        [53.40666667, 53.94367347, 55.40635294, 63.40189189],
        [41.19857143, 47.10241379, 45.711625  , 58.17612903]]),
 array([[45.30043478, 45.16923077, 42.85324324, 43.54545455,  0.        ],
        [28.9225    , 27.20521277, 31.14245455, 24.5165    ,  0.        ],
        [34.264375  , 30.44545455, 34.

Year 2005

In [ ]:
pixelYield_2005=[]
for j in range(72,88,1):
  x1=qgislatlong[j][1]
  y1=qgislatlong[j][2]
  x2=qgislatlong[j][3]
  y2=qgislatlong[j][4]
  x3=qgislatlong[j][5]
  y3=qgislatlong[j][6]
  x4=qgislatlong[j][7]
  y4=qgislatlong[j][8]
  farmPoly = Polygon(np.array([[x1,y1],[x2,y2],[x3,y3],[x4,y4]]))
  nrow=numberRC[j][3]
  ncol=numberRC[j][2]
  yd=(int(nrow),int(ncol))
  yd=np.zeros(yd)
  countyd=(int(nrow),int(ncol))
  countyd = np.zeros(countyd)
  horizontaldiff_x = (x2-x1)/ncol;
  verticaldiff_y = (y4-y1)/nrow;
  ans=(int(nrow),int(ncol))
  ans=np.zeros(ans)
  for i in range(0,int(X_2005.size/X_2005[0].size),1):
    point=Point(X_2005[i][0],X_2005[i][1])
    if point.within(farmPoly):
      for r in range(0,int(nrow),1):
        for c in range(0,int(ncol),1):
          pixelPoly= Polygon(np.array([[x1+(c*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)],[x1+((c)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)]]))
          if point.within(pixelPoly):
            yd[r][c]+=X_2005[i][2]
            countyd[r][c]+=1
  for k in range(0,int(nrow),1):
    for m in range(0,int(ncol),1):
      if countyd[k][m]!=0:
        ans[k][m]=yd[k][m]/countyd[k][m]
  pixelYield_2005.append(ans)

In [ ]:
pixelYield_2005

[array([[ 85.926     ,  71.85677419, 105.9416129 , 118.41395349],
        [106.48023256, 107.068625  , 136.8764    , 131.65177419],
        [107.99357143, 108.71666667, 140.7917    , 128.49655738],
        [ 71.99066667, 103.71888889, 110.77902174, 115.68622642],
        [ 53.99181818,   0.        ,   0.        ,   0.        ]]),
 array([[119.37914894,  76.2236    ,  82.76279412,  83.60918919],
        [131.47306452, 114.06304762, 116.39351852, 122.68222222],
        [128.64766667, 121.98190476, 127.76242991, 112.843     ],
        [111.7354717 , 116.73630435, 111.76364706,  93.04236364]]),
 array([[ 92.28727273,  74.34823529,  79.81107143,  54.79478261],
        [ 97.2652381 , 106.70284211, 104.1001087 , 106.17422222],
        [109.05886364, 114.08494624, 107.09234043, 106.00888889],
        [ 84.88243902,  88.46453333, 103.06909091, 121.84473684]]),
 array([[117.52116667, 114.50202532, 111.945375  ,  93.5547541 ,
           0.        ],
        [ 66.29071429,  70.33033708,  63.239111

Year 2006

In [ ]:
pixelYield_2006=[]
for j in range(88,112,1):
  x1=qgislatlong[j][1]
  y1=qgislatlong[j][2]
  x2=qgislatlong[j][3]
  y2=qgislatlong[j][4]
  x3=qgislatlong[j][5]
  y3=qgislatlong[j][6]
  x4=qgislatlong[j][7]
  y4=qgislatlong[j][8]
  farmPoly = Polygon(np.array([[x1,y1],[x2,y2],[x3,y3],[x4,y4]]))
  nrow=numberRC[j][3]
  ncol=numberRC[j][2]
  yd=(int(nrow),int(ncol))
  yd=np.zeros(yd)
  countyd=(int(nrow),int(ncol))
  countyd = np.zeros(countyd)
  horizontaldiff_x = (x2-x1)/ncol;
  verticaldiff_y = (y4-y1)/nrow;
  ans=(int(nrow),int(ncol))
  ans=np.zeros(ans)
  for i in range(0,int(X_2006.size/X_2006[0].size),1):
    point=Point(X_2006[i][0],X_2006[i][1])
    if point.within(farmPoly):
      for r in range(0,int(nrow),1):
        for c in range(0,int(ncol),1):
          pixelPoly= Polygon(np.array([[x1+(c*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)],[x1+((c)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)]]))
          if point.within(pixelPoly):
            yd[r][c]+=X_2006[i][2]
            countyd[r][c]+=1
  for k in range(0,int(nrow),1):
    for m in range(0,int(ncol),1):
      if countyd[k][m]!=0:
        ans[k][m]=yd[k][m]/countyd[k][m]
  pixelYield_2006.append(ans)

In [ ]:
pixelYield_2006

[array([[31.855     , 29.57205882, 30.40409836, 28.68108108],
        [36.49769231, 35.98      , 36.26989474, 35.5822807 ],
        [36.87175   , 34.77180851, 37.3644086 , 37.73538462],
        [31.11552632, 31.91202381, 35.00586207, 36.705     ],
        [21.18521739,  0.        ,  0.        , 27.04166667]]),
 array([[28.98309524, 34.57583333, 38.86728814, 31.49392157],
        [36.16737705, 37.18402174, 39.16567901, 35.5838806 ],
        [37.5994    , 37.17767442, 37.731875  , 34.93460317],
        [36.91076923, 36.94375   , 36.52686747, 36.97      ]]),
 array([[23.05333333, 25.13155556, 24.95704918, 20.38363636],
        [28.38357143, 29.92247619, 31.04943182, 29.09535714],
        [37.88021277, 29.3628    , 30.27701149, 28.44135135],
        [28.55083333, 26.52929577, 26.31126761, 28.98206897]]),
 array([[36.44216216, 36.85710526, 36.80866667, 36.54255814,  0.        ],
        [28.69111111, 89.85931034, 34.35142857, 30.22516667,  0.        ],
        [31.74846154, 34.41194805, 33.

Year 2007

In [ ]:
pixelYield_2007=[]
for j in range(112,136,1):
  x1=qgislatlong[j][1]
  y1=qgislatlong[j][2]
  x2=qgislatlong[j][3]
  y2=qgislatlong[j][4]
  x3=qgislatlong[j][5]
  y3=qgislatlong[j][6]
  x4=qgislatlong[j][7]
  y4=qgislatlong[j][8]
  farmPoly = Polygon(np.array([[x1,y1],[x2,y2],[x3,y3],[x4,y4]]))
  nrow=numberRC[j][3]
  ncol=numberRC[j][2]
  yd=(int(nrow),int(ncol))
  yd=np.zeros(yd)
  countyd=(int(nrow),int(ncol))
  countyd = np.zeros(countyd)
  horizontaldiff_x = (x2-x1)/ncol;
  verticaldiff_y = (y4-y1)/nrow;
  ans=(int(nrow),int(ncol))
  ans=np.zeros(ans)
  for i in range(0,int(X_2007.size/X_2007[0].size),1):
    point=Point(X_2007[i][0],X_2007[i][1])
    if point.within(farmPoly):
      for r in range(0,int(nrow),1):
        for c in range(0,int(ncol),1):
          pixelPoly= Polygon(np.array([[x1+(c*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)],[x1+((c)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)]]))
          if point.within(pixelPoly):
            yd[r][c]+=X_2007[i][2]
            countyd[r][c]+=1
  for k in range(0,int(nrow),1):
    for m in range(0,int(ncol),1):
      if countyd[k][m]!=0:
        ans[k][m]=yd[k][m]/countyd[k][m]
  pixelYield_2007.append(ans)

In [ ]:
pixelYield_2007

[array([[46.96      , 27.93423077, 47.6545283 , 45.72275862],
        [59.48971429, 49.57107143, 56.4448    , 52.95      ],
        [56.82346154, 53.72602273, 55.91653061, 54.091875  ],
        [47.37192308, 45.69271605, 46.65836957, 51.005     ],
        [39.94095238,  0.        ,  0.        , 34.92666667]]),
 array([[47.68121212, 32.468     , 36.24145455, 33.99142857],
        [52.13018868, 37.37548387, 41.35710145, 43.32032787],
        [54.52311111, 38.05364583, 44.37444444, 40.00806452],
        [51.005625  , 38.52233766, 42.18214286, 39.06865385]]),
 array([[24.67071429, 28.39952381, 33.83484848, 38.971     ],
        [37.73857143, 37.45897959, 46.39810127, 46.13266667],
        [42.82771429, 34.08197917, 41.31797101, 36.83714286],
        [37.99606061, 30.36987952, 38.82786885, 38.81689655]]),
 array([[49.04195122, 38.49985915, 42.20462963, 38.88627451,  0.        ],
        [34.59      , 28.31296875, 29.93275362, 28.7314    ,  0.        ],
        [32.68181818, 29.97166667, 31.

Year 2008

In [ ]:
pixelYield_2008=[]
for j in range(136,160,1):
  x1=qgislatlong[j][1]
  y1=qgislatlong[j][2]
  x2=qgislatlong[j][3]
  y2=qgislatlong[j][4]
  x3=qgislatlong[j][5]
  y3=qgislatlong[j][6]
  x4=qgislatlong[j][7]
  y4=qgislatlong[j][8]
  farmPoly = Polygon(np.array([[x1,y1],[x2,y2],[x3,y3],[x4,y4]]))
  nrow=numberRC[j][3]
  ncol=numberRC[j][2]
  yd=(int(nrow),int(ncol))
  yd=np.zeros(yd)
  countyd=(int(nrow),int(ncol))
  countyd = np.zeros(countyd)
  horizontaldiff_x = (x2-x1)/ncol;
  verticaldiff_y = (y4-y1)/nrow;
  ans=(int(nrow),int(ncol))
  ans=np.zeros(ans)
  for i in range(0,int(X_2008.size/X_2008[0].size),1):
    point=Point(X_2008[i][0],X_2008[i][1])
    if point.within(farmPoly):
      for r in range(0,int(nrow),1):
        for c in range(0,int(ncol),1):
          pixelPoly= Polygon(np.array([[x1+(c*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)],[x1+((c)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)]]))
          if point.within(pixelPoly):
            yd[r][c]+=X_2008[i][2]
            countyd[r][c]+=1
  for k in range(0,int(nrow),1):
    for m in range(0,int(ncol),1):
      if countyd[k][m]!=0:
        ans[k][m]=yd[k][m]/countyd[k][m]
  pixelYield_2008.append(ans)

In [ ]:
pixelYield_2008

[array([[ 53.12333333,  60.72931034, 101.6784    ,  93.78897436],
        [ 88.48468085,  81.70945055, 112.89705882,  92.02241935],
        [ 89.52042553,  89.33276596, 116.04754386,  81.83421875],
        [ 67.97568182,  93.53372093,  84.29063063,  89.339     ],
        [ 37.13043478,   0.        ,   0.        ,  27.27      ]]),
 array([[94.96418605, 48.50308824, 61.50971831, 59.26      ],
        [91.29918033, 67.60941176, 79.66088889, 84.59111111],
        [81.43661538, 74.40647059, 98.27083333, 71.69380282],
        [89.06513514, 72.93829268, 71.108     , 53.81072727]]),
 array([[56.1744    , 46.48462687, 58.8127451 , 41.43172414],
        [57.08604167, 64.89229358, 76.27891304, 81.71488889],
        [69.24458333, 75.44140351, 88.22833333, 74.81021277],
        [62.54487805, 57.8335443 , 76.2637931 , 96.12666667]]),
 array([[88.99540541, 70.17169014, 73.05957746, 52.98134615,  0.        ],
        [28.08230769, 33.28988889, 30.90529412, 33.31360656,  0.        ],
        [38.045333

Year 2009

In [ ]:
pixelYield_2009=[]
for j in range(160,184,1):
  x1=qgislatlong[j][1]
  y1=qgislatlong[j][2]
  x2=qgislatlong[j][3]
  y2=qgislatlong[j][4]
  x3=qgislatlong[j][5]
  y3=qgislatlong[j][6]
  x4=qgislatlong[j][7]
  y4=qgislatlong[j][8]
  farmPoly = Polygon(np.array([[x1,y1],[x2,y2],[x3,y3],[x4,y4]]))
  nrow=numberRC[j][3]
  ncol=numberRC[j][2]
  yd=(int(nrow),int(ncol))
  yd=np.zeros(yd)
  countyd=(int(nrow),int(ncol))
  countyd = np.zeros(countyd)
  horizontaldiff_x = (x2-x1)/ncol;
  verticaldiff_y = (y4-y1)/nrow;
  ans=(int(nrow),int(ncol))
  ans=np.zeros(ans)
  for i in range(0,int(X_2009.size/X_2009[0].size),1):
    point=Point(X_2009[i][0],X_2009[i][1])
    if point.within(farmPoly):
      for r in range(0,int(nrow),1):
        for c in range(0,int(ncol),1):
          pixelPoly= Polygon(np.array([[x1+(c*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)],[x1+((c)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)]]))
          if point.within(pixelPoly):
            yd[r][c]+=X_2009[i][2]
            countyd[r][c]+=1
  for k in range(0,int(nrow),1):
    for m in range(0,int(ncol),1):
      if countyd[k][m]!=0:
        ans[k][m]=yd[k][m]/countyd[k][m]
  pixelYield_2009.append(ans)

In [ ]:
pixelYield_2009

[array([[14.65428571, 16.58525   , 14.34517241, 21.03428571],
        [25.05225   , 24.3554955 , 24.58375   , 23.68536232],
        [23.56769231, 25.0627027 , 24.26525641, 22.94294118],
        [15.93631579, 20.28609091, 21.41044118, 16.36      ],
        [46.58777778,  0.        ,  0.        , 26.715     ]]),
 array([[21.38644444, 21.21906977, 19.29917647, 21.81648649],
        [23.59057971, 25.42096774, 26.91606299, 25.01237288],
        [22.81714286, 26.50904   , 29.15645669, 24.2957377 ],
        [15.19      , 20.74784091, 22.82819277, 15.70553191]]),
 array([[38.81411765, 49.02711111, 42.98161765, 47.66333333],
        [50.63660714, 51.89526316, 48.51881818, 50.85428571],
        [58.92734694, 54.22106796, 50.42782178, 49.83657895],
        [44.61527778, 46.87692308, 43.40444444, 47.9404878 ]]),
 array([[15.97604167, 19.681375  , 22.478     , 15.32545455,  0.        ],
        [26.62090909, 22.85839506, 20.97443182, 21.21521127,  0.        ],
        [18.42666667, 24.34228261, 21.

Year 2010

In [ ]:
pixelYield_2010=[]
for j in range(184,208,1):
  x1=qgislatlong[j][1]
  y1=qgislatlong[j][2]
  x2=qgislatlong[j][3]
  y2=qgislatlong[j][4]
  x3=qgislatlong[j][5]
  y3=qgislatlong[j][6]
  x4=qgislatlong[j][7]
  y4=qgislatlong[j][8]
  farmPoly = Polygon(np.array([[x1,y1],[x2,y2],[x3,y3],[x4,y4]]))
  nrow=numberRC[j][3]
  ncol=numberRC[j][2]
  yd=(int(nrow),int(ncol))
  yd=np.zeros(yd)
  countyd=(int(nrow),int(ncol))
  countyd = np.zeros(countyd)
  horizontaldiff_x = (x2-x1)/ncol;
  verticaldiff_y = (y4-y1)/nrow;
  ans=(int(nrow),int(ncol))
  ans=np.zeros(ans)
  for i in range(0,int(X_2010.size/X_2010[0].size),1):
    point=Point(X_2010[i][0],X_2010[i][1])
    if point.within(farmPoly):
      for r in range(0,int(nrow),1):
        for c in range(0,int(ncol),1):
          pixelPoly= Polygon(np.array([[x1+(c*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)],[x1+((c)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)]]))
          if point.within(pixelPoly):
            yd[r][c]+=X_2010[i][2]
            countyd[r][c]+=1
  for k in range(0,int(nrow),1):
    for m in range(0,int(ncol),1):
      if countyd[k][m]!=0:
        ans[k][m]=yd[k][m]/countyd[k][m]
  pixelYield_2010.append(ans)

In [ ]:
pixelYield_2010

[array([[617.835     ,  46.99392857,  47.37571429,  40.6362    ],
        [ 51.23521739,  48.456875  ,  51.963     ,  45.66980198],
        [ 41.49318182,  48.83481928,  50.91617978,  46.60583333],
        [ 46.94641026,  76.60254902,  51.55470588,  43.40921053],
        [ 39.23708333,   0.        ,   0.        ,  38.24541667]]),
 array([[40.43606557, 40.93813187, 40.18619048, 39.71464286],
        [46.19051546, 42.29809249, 39.09701613, 40.55421569],
        [45.97021053, 44.9052381 , 41.56447154, 42.76754902],
        [42.85977778, 45.73858156, 41.95526718, 40.24282609]]),
 array([[36.83545455, 35.85319149, 42.78442623, 39.86173913],
        [36.1975    , 29.80298969, 42.11876404, 32.28285714],
        [29.51526316, 23.1312    , 34.47931034, 28.28382353],
        [35.73105263, 36.74742268, 35.655625  , 31.01166667]]),
 array([[ 43.31736111,  45.28212329,  41.93259843,  40.10744186,
           0.        ],
        [ 38.57285714,  36.95238532,  41.00353383, 360.07253968,
           0. 

Year 2011

In [ ]:
pixelYield_2011=[]
for j in range(208,232,1):
  x1=qgislatlong[j][1]
  y1=qgislatlong[j][2]
  x2=qgislatlong[j][3]
  y2=qgislatlong[j][4]
  x3=qgislatlong[j][5]
  y3=qgislatlong[j][6]
  x4=qgislatlong[j][7]
  y4=qgislatlong[j][8]
  farmPoly = Polygon(np.array([[x1,y1],[x2,y2],[x3,y3],[x4,y4]]))
  nrow=numberRC[j][3]
  ncol=numberRC[j][2]
  yd=(int(nrow),int(ncol))
  yd=np.zeros(yd)
  countyd=(int(nrow),int(ncol))
  countyd = np.zeros(countyd)
  horizontaldiff_x = (x2-x1)/ncol;
  verticaldiff_y = (y4-y1)/nrow;
  ans=(int(nrow),int(ncol))
  ans=np.zeros(ans)
  for i in range(0,int(X_2011.size/X_2011[0].size),1):
    point=Point(X_2011[i][0],X_2011[i][1])
    if point.within(farmPoly):
      for r in range(0,int(nrow),1):
        for c in range(0,int(ncol),1):
          pixelPoly= Polygon(np.array([[x1+(c*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)],[x1+((c)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)]]))
          if point.within(pixelPoly):
            yd[r][c]+=X_2011[i][2]
            countyd[r][c]+=1
  for k in range(0,int(nrow),1):
    for m in range(0,int(ncol),1):
      if countyd[k][m]!=0:
        ans[k][m]=yd[k][m]/countyd[k][m]
  pixelYield_2011.append(ans)

In [ ]:
pixelYield_2011

[array([[183.175     ,  66.8571875 , 148.40528302, 150.73839506],
        [177.79151515, 169.01864   , 174.19494382, 181.40174312],
        [174.15590909, 168.65590909, 185.53367816, 177.91533981],
        [120.71408451, 147.96320896, 240.68266234, 163.81236842],
        [155.56862069,   0.        ,   0.        ,  79.97428571]]),
 array([[154.65351648, 133.03515152, 243.11492308, 138.01296296],
        [177.74      , 176.77018519, 190.33884817, 172.84929293],
        [176.67365854, 183.9039759 , 201.7188601 , 167.02019802],
        [161.82824324, 167.89710744, 156.26245614, 169.46880952]]),
 array([[167.6325    , 120.31346154, 152.66901786, 153.6804    ],
        [174.26980198, 183.74755102, 180.58752874, 173.8898    ],
        [186.47782178, 178.64910959, 181.29939227, 165.81204082],
        [143.07632653, 147.02699115, 161.81068493, 151.93241379]]),
 array([[166.25277108, 166.13113043, 150.99989899, 173.52866667,
           0.        ],
        [ 82.19875   ,  66.23767677,  71.756867

Year 2012

In [ ]:
pixelYield_2012=[]
for j in range(232,252,1):
  x1=qgislatlong[j][1]
  y1=qgislatlong[j][2]
  x2=qgislatlong[j][3]
  y2=qgislatlong[j][4]
  x3=qgislatlong[j][5]
  y3=qgislatlong[j][6]
  x4=qgislatlong[j][7]
  y4=qgislatlong[j][8]
  farmPoly = Polygon(np.array([[x1,y1],[x2,y2],[x3,y3],[x4,y4]]))
  nrow=numberRC[j][3]
  ncol=numberRC[j][2]
  yd=(int(nrow),int(ncol))
  yd=np.zeros(yd)
  countyd=(int(nrow),int(ncol))
  countyd = np.zeros(countyd)
  horizontaldiff_x = (x2-x1)/ncol;
  verticaldiff_y = (y4-y1)/nrow;
  ans=(int(nrow),int(ncol))
  ans=np.zeros(ans)
  for i in range(0,int(X_2012.size/X_2012[0].size),1):
    point=Point(X_2012[i][0],X_2012[i][1])
    if point.within(farmPoly):
      for r in range(0,int(nrow),1):
        for c in range(0,int(ncol),1):
          pixelPoly= Polygon(np.array([[x1+(c*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+(r*verticaldiff_y)],[x1+((c+1)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)],[x1+((c)*horizontaldiff_x),y1+((r+1)*verticaldiff_y)]]))
          if point.within(pixelPoly):
            yd[r][c]+=X_2012[i][2]
            countyd[r][c]+=1
  for k in range(0,int(nrow),1):
    for m in range(0,int(ncol),1):
      if countyd[k][m]!=0:
        ans[k][m]=yd[k][m]/countyd[k][m]
  pixelYield_2012.append(ans)

In [ ]:
pixelYield_2012

[array([[29.73333333, 37.27307692, 36.23897959, 35.13891892],
        [34.20111111, 31.43619048, 35.24782178, 30.93220588],
        [33.10318182, 29.40078431, 33.409     , 32.39714286],
        [35.60416667, 35.96513761, 49.90184211, 33.44      ],
        [24.8340625 ,  0.        ,  0.        ,  0.        ]]),
 array([[34.45767442, 26.15983871, 31.89521127, 30.71688889],
        [30.33204819, 25.02045977, 28.86295455, 25.69178571],
        [31.95277108, 23.76      , 29.128     , 24.88862069],
        [32.56653333, 33.70860759, 32.22633333, 24.19918919]]),
 array([[32.35956522, 24.34225   , 27.87943662, 24.794     ],
        [19.87583333, 23.49580247, 25.21588889, 23.17166667],
        [21.9874    , 22.817875  , 26.19064516, 22.18428571],
        [23.98868421, 26.49014706, 30.2545679 , 24.91346154]]),
 array([[ 33.75970149,  32.38746835,  34.0954386 ,  23.46425   ,
           0.        ],
        [  0.        ,  20.35674699,  18.35576471,  18.07393939,
           0.        ],
        [ 

In [ ]:
pixelYieldTotal=[]

In [ ]:
for i in range(0,24,1):
  pixelYieldTotal.append(pixelYield_2001[i])
for i in range(0,24,1):
  pixelYieldTotal.append(pixelYield_2003[i])
for i in range(0,24,1):
  pixelYieldTotal.append(pixelYield_2004[i])
for i in range(0,16,1):
  pixelYieldTotal.append(pixelYield_2005[i])
for i in range(0,24,1):
  pixelYieldTotal.append(pixelYield_2006[i])
for i in range(0,24,1):
  pixelYieldTotal.append(pixelYield_2007[i])
for i in range(0,24,1):
  pixelYieldTotal.append(pixelYield_2008[i])
for i in range(0,24,1):
  pixelYieldTotal.append(pixelYield_2009[i])
for i in range(0,24,1):
  pixelYieldTotal.append(pixelYield_2010[i])
for i in range(0,24,1):
  pixelYieldTotal.append(pixelYield_2011[i])
for i in range(0,20,1):
  pixelYieldTotal.append(pixelYield_2012[i])

In [ ]:
pixelYieldTotal

[array([[ 22.44733333,  27.06982143,  35.75      ,  44.9716    ],
        [ 37.03911765,  44.21717742,  49.35563636,  48.3822619 ],
        [ 37.81857143,  41.79210938,  53.81545455,  48.24964286],
        [173.05368421,  31.19976   ,  40.99298969,  36.72648649],
        [ 44.90333333,   0.        ,   0.        ,   0.        ]]),
 array([[45.95803571, 40.46957746, 42.78456522, 43.73070175],
        [47.86373494, 49.42338843, 50.21765101, 43.29877551],
        [48.46928571, 50.46974576, 51.88583893, 46.97378947],
        [34.41      , 39.76868687, 44.87904762, 38.41      ]]),
 array([[44.59324324, 39.0576087 , 45.59178947, 44.1064    ],
        [56.77052632, 56.8692562 , 56.72970149, 54.18319149],
        [56.30310345, 55.17540984, 55.86969697, 56.203125  ],
        [46.23530612, 45.64072727, 48.84936937, 39.44107143]]),
 array([[34.05112676, 39.72123711, 44.29628099, 37.79714286,  0.        ],
        [ 0.85      , 34.83803571, 29.12659259, 26.6927957 ,  0.        ],
        [ 0.      

In [ ]:
numberRC[0]

array([ 1., 20.,  4.,  5.])

In [ ]:
pixelYieldTotal[0]


array([[ 22.44733333,  27.06982143,  35.75      ,  44.9716    ],
       [ 37.03911765,  44.21717742,  49.35563636,  48.3822619 ],
       [ 37.81857143,  41.79210938,  53.81545455,  48.24964286],
       [173.05368421,  31.19976   ,  40.99298969,  36.72648649],
       [ 44.90333333,   0.        ,   0.        ,   0.        ]])

In [ ]:
yieldFinal=[]
excluded=[42,43,44,45,46,86,87,88,119,120,121,122,125,126,128,129,130,132,133]
for i in range(0,252,1):
  if i+1 in excluded:
    continue
  r=int(numberRC[i][3])
  c=int(numberRC[i][2])
  for k in range(0,r-1,1):
    for m in range(0,c-1,1):
      sum=0
      sum=pixelYieldTotal[i][k][m]+pixelYieldTotal[i][k][m+1]+pixelYieldTotal[i][k+1][m]+pixelYieldTotal[i][k+1][m+1]
      yieldFinal.append(sum/4)

In [ ]:
len(yieldFinal)

2884

In [ ]:
for i in range(0,500,1):
  print(yieldFinal[i])

32.69336245707961
39.09815880289066
44.61487456709956
40.21674396749627
47.295094425861436
49.950748917748925
70.96603125352443
41.95007840279405
44.94614339495138
62.28919438596491
18.048187422680414
19.42986904430203
45.92868413714639
45.723795529660876
45.00792337217319
49.05653871162717
50.499156031337456
48.09401372919355
43.27942958642111
46.75082979415521
45.537169004726586
49.322658613258
49.56208896505521
50.152770613895825
56.27957394961949
56.16101612416174
55.74642873789901
50.83863666987942
51.3838008619648
50.090815691909455
27.365099897062784
36.99553660300398
34.478203035098936
16.1224846390169
17.925004796340026
34.31107481948816
31.421591782524995
14.823021759376855
17.982385631548127
36.73590560781394
35.30826281091149
16.55474283464568
21.898155340103518
33.917446893750295
35.64732749567577
17.193452608695655
20.21636666666667
24.125662068965507
36.68533179893066
47.76728495062989
53.44667657573533
51.01360360973075
53.901322890250185
58.15192837231605
53.4183218979

In [ ]:
for i in range(500,1000,1):
  print(yieldFinal[i])

8.098355855855853
15.363555782786115
15.02924307011666
7.764043143186401
7.662768201875341
14.340374438308807
15.4794127198832
8.801806483449738
11.800595440879054
15.70076224272316
16.127545990338287
8.548065463003987
8.405302058273186
16.80019907531864
18.05383511228355
189.4080353174603
9.428257091745465
18.349715196893328
19.356205724195483
10.434747619047616
10.430292628719595
20.60947937570755
20.22912722317843
10.049940476190475
9.908894963884432
19.22964633299725
17.753489464350913
8.432738095238095
18.454955636461705
46.892158761461744
43.048057776162835
24.923351660926542
60.99273963878687
61.56595096235645
24.979848911728368
37.38508056731761
40.44836844943722
23.675004474565117
22.24978361425059
22.28491593353345
40.53534948797332
44.90009228827647
50.80327367268747
49.64017257085019
51.48398781810293
55.18085118128761
48.51466062287682
49.513777994823315
51.93264042729926
35.532475381461325
23.730899199276777
31.236901314977164
46.08301312008469
42.96038401793575
46.445774

In [ ]:
for i in range(1000,1500,1):
  print(yieldFinal[i])

33.05651298025681
32.73433872008333
36.03031270458265
36.09652796240772
36.73799216403291
33.667777158987896
34.763525747819536
36.702663821625165
21.053191879154408
16.72947146962233
24.688132183908042
34.227581839934835
37.44820555510067
36.27769232839532
37.03211830172886
37.814812542520194
36.85400944599095
37.15789841234347
37.09504172212104
36.54083641112067
26.62273412698412
27.765128186135364
26.371368626250806
31.38726509625126
30.15292987572772
29.715787951660808
30.580785468484667
28.120093718633644
28.50292485418882
47.96242222031469
49.46912771152018
34.48195501107419
16.69193120155039
46.17770776158707
48.00615561301879
32.32455203533026
15.386211021505376
33.28976051726051
34.015570299159435
32.70181047343372
15.880616076150186
34.01919545732045
36.90133391781547
36.76138850348482
17.30160581222057
10.514638111888111
11.39294374282434
20.11995698490141
23.83244459336959
25.166984260065718
27.696079667011816
32.12803607331822
32.23286561469609
28.90970556146576
30.6039795

In [ ]:
for i in range(1500,2000,1):
  print(yieldFinal[i])

48.709129224063446
57.38063742638744
65.68405758966323
62.71758208789346
57.52025441919192
60.49360115615106
62.90122344912089
55.420824816245364
53.869134792428234
61.49570673182589
73.73189470108697
100.87532708333332
69.72080850787069
92.73234680147202
115.72976095063025
73.99667255281999
99.63745507839464
112.94528590363043
72.02494070974507
90.69162116539476
93.38562293626956
81.50677184865646
54.744689946183954
56.346965492278
117.64291289087944
123.05560235320284
119.29296230350249
116.64008505357573
122.3682707444513
116.17986352345964
87.62661683332246
87.84331354164848
85.46503170666102
74.7639771302638
45.30387886195079
57.54466686704914
34.25432359307359
88.73103406142788
64.75074837377116
72.02947175459533
40.771366765764355
93.47905852838986
75.40339235167751
75.6331096993014
38.600420623671155
75.72516538793957
79.07699180947864
79.2270782555031
35.30197904915391
66.83508823538193
84.64258958123884
78.61571157681892
75.37244132966813
92.59419100770815
82.20717327848376
7

In [ ]:
for i in range(2000,2500,1):
  print(yieldFinal[i])

30.72243281450049
31.453528438653464
32.483131564849124
33.460865347859325
34.00733405195908
28.26803156206475
26.12413551506276
26.055904881757336
11.84502096436059
45.40234457037826
42.61146642001761
27.06855382260755
13.51961765239478
46.841826470531025
42.51452084794638
27.593857526504145
13.945705726176808
33.74772473118279
60.03219646007007
77.0144832375711
37.66961107578339
24.645294949494946
22.861668227163918
42.18756463569366
29.882524691358025
26.909108585858583
24.70373936701269
25.039141927096285
11.821147509578545
17.8234803030303
24.158670246734395
23.71507722807979
9.731023648012062
13.669594691535156
15.744152915148366
10.066399313707787
20.79351339782886
24.36028306624727
18.12950655154973
20.05367010685393
20.721290281817858
13.890968348953058
13.570751400560223
11.772576797385621
11.041986111111111
191.13025524068317
48.69737946428572
46.411179066478084
47.50502337164865
50.04271851309734
48.78870377220308
53.4692400928271
56.97706348858755
48.12148237932075
40.6965

In [ ]:
for i in range(2500,2884,1):
  print(yieldFinal[i])

174.99590640850076
112.5532765001731
119.8768533637724
129.57408127289378
53.789916470588224
123.55586268859226
151.48980596936377
81.72385975135973
77.45473999999999
162.3362750877193
174.08202597343143
89.20049088571211
76.71637162162162
160.68953157227952
168.10025645297566
84.12709650231776
64.35914056101555
111.63830130912163
105.40379278273812
41.96273809523811
139.59533717672085
150.50477000601197
147.33056106096282
149.5130077302034
172.79268309094113
180.68135914796497
126.37955234446358
154.092157726521
171.26745015657906
95.42974835844132
101.57360358042601
113.20240170360427
87.27046616502867
88.26243225918229
89.17241581335333
97.59194308410613
101.26772700157755
101.58763276307026
84.46797396741704
93.17059322932943
97.2426503692386
76.69948636955128
71.38868661520587
70.38618202301467
49.3315376984127
102.20129393479414
82.03893782891524
84.90603228124745
45.42246733449477
101.43543896179804
75.0315605052862
84.29901525642902
46.56502090592333
122.06715439475876
122.3179

In [ ]:
print(yieldFinal[2883])

27.576087972575984
